version: "3.3"
services:
  www:
    image: voxbox/nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"      
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80  
    deploy:      
      restart_policy:
        condition: on-failure  
    networks:
      - www  
networks:
  www: 