#!/bin/bash
set -e

DH="${HOME}/ssl/dh.pem"
agent_conf_file="/etc/amplify-agent/agent.conf"
agent_log_file="/var/log/amplify-agent/agent.log"
nginx_status_conf="${HOME}/conf.d/stub_status.conf"
api_key=""
amplify_imagename=""

set_default_config() {
  envsubst \$NGINX_HOST < ${HOME}/conf.d/ssl.conf > ${HOME}/conf.d/default.conf
  rm ${HOME}/conf.d/ssl.conf
}

create_dh() {
    if [ ! -e "$DH" ]
    then
        echo ">> Generating $DH with size: $DH_SIZE"
        openssl dhparam -out "$DH" $DH_SIZE
    fi
}

create_cert() {   
    if [ ! -e "${HOME}/ssl/cert.pem" ] || [ ! -e "${HOME}/ssl/key.pem" ]
    then
        echo ">> Generating self-signed SSL certificate"
        openssl req -x509 -newkey rsa:4086 \
        -subj "/C=XX/ST=XXXX/L=XXXX/O=XXXX/CN=localhost" \
        -keyout "${HOME}/ssl/key.pem" \
        -out "${HOME}/ssl/cert.pem" \
        -days 365 -nodes -sha256
    fi
}

setup_amplify() {

test -n "${API_KEY}" && \
    api_key=${API_KEY}

test -n "${AMPLIFY_IMAGENAME}" && \
    amplify_imagename=${AMPLIFY_IMAGENAME}

if [ -n "${api_key}" -o -n "${amplify_imagename}" ]; then
    echo "updating ${agent_conf_file} ..."

    if [ ! -f "${agent_conf_file}" ]; then
      test -f "${agent_conf_file}.default" && \
      cp -p "${agent_conf_file}.default" "${agent_conf_file}" || \
      { echo "no ${agent_conf_file}.default found! exiting."; exit 1; }
    fi

    test -n "${api_key}" && \
    echo " ---> using api_key = ${api_key}" && \
    sh -c "sed -i.old -e 's/api_key.*$/api_key = $api_key/' \
	${agent_conf_file}"

    test -n "${amplify_imagename}" && \
    echo " ---> using imagename = ${amplify_imagename}" && \
    sh -c "sed -i.old -e 's/imagename.*$/imagename = $amplify_imagename/' \
	${agent_conf_file}"

    test -f "${agent_conf_file}" && \
    chmod 644 ${agent_conf_file} && \
    chown nginx ${agent_conf_file} > /dev/null 2>&1

    test -f "${nginx_status_conf}" && \
    chmod 644 ${nginx_status_conf} && \
    chown nginx ${nginx_status_conf} > /dev/null 2>&1
fi

if ! grep '^api_key.*=[ ]*[[:alnum:]].*' ${agent_conf_file} > /dev/null 2>&1; then
    echo "no api_key found in ${agent_conf_file}! exiting."
fi

echo "starting amplify-agent ..."
service amplify-agent start > /dev/null 2>&1 < /dev/null

if [ $? != 0 ]; then
    echo "couldn't start the agent, please check ${agent_log_file}"
    exit 1
fi

}

